{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "disabled-attack",
   "metadata": {},
   "source": [
    "# Debugging A Simple Image Processing Program Using The Compute Sanitizer\n",
    "## 04 Memcheck part 2\n",
    "\n",
    "In this section, we will continue on the memcheck tool to explore a new option\n",
    "that was added with the compute-sanitizer version released with CUDA 11.3.\n",
    "\n",
    "In the current state of the program, as we saw previously something is still off\n",
    "as in the left part of the image some pixels are not colored correctly. Let's try to run memcheck again:\n",
    "\n",
    "\n",
    "```\n",
    "========= COMPUTE-SANITIZER\n",
    "Image ./checkerboard.png size: 32 * 32\n",
    "Image ./icon.png size: 32 * 32\n",
    "Grid size: 2 * 2 * 1\n",
    "Block size: 31 * 31 * 1\n",
    "Grid size: 2 * 2 * 1\n",
    "Block size: 31 * 31 * 1\n",
    "========= ERROR SUMMARY: 0 errors\n",
    "\n",
    "```\n",
    "\n",
    "No errors are reported. At this point we could have several hypothesis:\n",
    "\n",
    "- The program doesn't do any undefined behavior and the problem is purely in its\n",
    "  logic, in which case, using the CUDA debugger would be a better option for\n",
    "  debugging.\n",
    "- The program has an undefined behavior that could be detected by another tool,\n",
    "  or that the compute-sanitizer cannot help with\n",
    "- The program does out of bound accesses, but ends up in a\n",
    "  neighboring allocation, which makes the access seen as valid while it would\n",
    "  not be.\n",
    "- ...\n",
    "\n",
    "Indeed, for the latter point, depending on the size of the allocations and their\n",
    "alignment, allocations can be directly consecutive in the virtual address space,\n",
    "meaning that going out of bound of a first allocation might result in an access\n",
    "in the following allocation which is seen as valid. As a countermeasure to this\n",
    "issue, the compute-sanitizer introduced the flag `--padding` which makes the\n",
    "compute-sanitizer add some padding bytes between allocations in order to avoid\n",
    "said consecutive allocation and better detect out of bound accesses in such\n",
    "case. This can have further impact on the memory consumption and performances of\n",
    "the program and is therefore not enabled by default.\n",
    "Let's see if that flag can help us:\n",
    "\n",
    "\n",
    "```sh\n",
    "    compute-sanitizer --padding=1 ./convolution\n",
    "```\n",
    "\n",
    "We observe this output:\n",
    "\n",
    "\n",
    "```\n",
    "========= COMPUTE-SANITIZER\n",
    "Image ./checkerboard.png size: 32 * 32\n",
    "Image ./icon.png size: 32 * 32\n",
    "Grid size: 2 * 2 * 1\n",
    "Block size: 31 * 31 * 1\n",
    "========= Invalid __global__ write of size 1 bytes\n",
    "=========     at 0x7800 in /home/nvidia/sanitizer-demo/convolution.cu:135:convolution(pixel const*, int, int, float const*, int, pixel*)\n",
    "=========     by thread (1,0,0) in block (1,1,0)\n",
    "=========     Address 0x7f1397001003 is out of bounds\n",
    "=========     Saved host backtrace up to driver entry point at kernel launch time\n",
    "=========     Host Frame: [0x27e53a]\n",
    "=========                in /usr/lib/x86_64-linux-gnu/libcuda.so.1\n",
    "=========     Host Frame: [0x1053b]\n",
    "=========                in /home/nvidia/sanitizer-demo/./convolution\n",
    "=========     Host Frame: [0x5bf60]\n",
    "=========                in /home/nvidia/sanitizer-demo/./convolution\n",
    "=========     Host Frame: [0xae3e]\n",
    "=========                in /home/nvidia/sanitizer-demo/./convolution\n",
    "=========     Host Frame:__device_stub__Z11convolutionPK5pixeliiPKfiPS_(pixel const *, int, int, float const *, int, pixel*) [0xac7b]\n",
    "=========                in /home/nvidia/sanitizer-demo/./convolution\n",
    "=========     Host Frame:convolution(pixel const *, int, int, float const *, int, pixel*) [0xace8]\n",
    "=========                in /home/nvidia/sanitizer-demo/./convolution\n",
    "=========     Host Frame: [0xa298]\n",
    "=========                in /home/nvidia/sanitizer-demo/./convolution\n",
    "=========     Host Frame:main [0xa7ca]\n",
    "=========                in /home/nvidia/sanitizer-demo/./convolution\n",
    "=========     Host Frame:__libc_start_main [0x270b3]\n",
    "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
    "=========     Host Frame:_start [0x9c0e]\n",
    "=========                in /home/nvidia/sanitizer-demo/./convolution\n",
    "========= \n",
    "========= Program hit unspecified launch failure (error 719) on CUDA API call to cudaDeviceSynchronize.\n",
    "=========     Saved host backtrace up to driver entry point at error\n",
    "=========     Host Frame: [0x54b673]\n",
    "=========                in /usr/lib/x86_64-linux-gnu/libcuda.so.1\n",
    "=========     Host Frame: [0x3cbc7]\n",
    "=========                in /home/nvidia/sanitizer-demo/./convolution\n",
    "=========     Host Frame: [0xa2ba]\n",
    "=========                in /home/nvidia/sanitizer-demo/./convolution\n",
    "=========     Host Frame:main [0xa7ca]\n",
    "=========                in /home/nvidia/sanitizer-demo/./convolution\n",
    "=========     Host Frame:__libc_start_main [0x270b3]\n",
    "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
    "=========     Host Frame:_start [0x9c0e]\n",
    "=========                in /home/nvidia/sanitizer-demo/./convolution\n",
    "========= \n",
    "GPU error: unspecified launch failure at convolution.cu:183\n",
    "========= Target application returned an error\n",
    "========= ERROR SUMMARY: 2 errors\n",
    "\n",
    "```\n",
    "\n",
    "We can now see errors that were previously undetected. Using this new\n",
    "information, take a moment to try to find the error. The solution is in the following collapsed cell:"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "included-trinity",
   "metadata": {
    "jupyter": {
     "source_hidden": true
    },
    "tags": []
   },
   "source": [
    "The error is located at line 110, where `xIdx > width` should be `xIdx >= width`, as the x index equal to width would be out of bounds by one."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "welcome-cooperative",
   "metadata": {},
   "source": [
    "Fix the mistake, recompile and run the program again. If we are lucky, we should see the correct output for [checkerboard-out.png](code/checkerboard-out.png) and [icon-out.png](code/icon-out.png), but this is not a guarantee as there is still a problem remaining in the code.\n",
    "\n",
    "[Continue to step 05.](05_racecheck.ipynb)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
